import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./styles/header-styles.css"
import "./styles/admin-panel-styles.css"
import "./styles/bottom-menu.css"
import { Toaster } from 'react-hot-toast';
import Script from 'next/script';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Toaster
          position="bottom-right"
          reverseOrder={false}
        />
        <Script src="https://cdn.lordicon.com/lordicon.js" strategy="afterInteractive"/>
      </body>
    </html>
  );
}
